name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - master

env:
  PROJECT_ID: myluk-496908
  REGION: us-west1
  SERVICE: myluk
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Clear problematic annotations
        run: gcloud run services update ${{ env.SERVICE }} --region ${{ env.REGION }} --remove-annotations "[run.googleapis.com/sources]" || true

      - name: Build and Deploy to Cloud Run
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE }}:${{ github.sha }}"
          gcloud builds submit --tag $IMAGE .
          gcloud run deploy ${{ env.SERVICE }} --image $IMAGE --region ${{ env.REGION }} --port 3000 --allow-unauthenticated
